### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by peter-ruse** [thepeaklab/GoogleMapsTileOverlay#1]
This doesn't render any custom tile overlays for me. Is iOS 12 not compatible?

**Comment by sandammeer** [comment]
Hey @peter-ruse the framework is compatible with iOS 12.
Can you provide more informations about your problem? 
Did you get an error code? 
Have you checked if the JSON file with the mapstyle is in a valid JSON-format?

**Comment by sandammeer** [comment]
Hello @peter-ruse, were you able to fix this issue for yourself on iOS 12?
