### ISSUE TITLE
Add support for CocoaPods

### ISSUE THREAD

**Issue by SebastianThiebaud** [thepeaklab/GoogleMapsTileOverlay#2]
Adding a podpsec to this repo and publishing it for CocoaPods would be great. Thanks.

**Comment by brunodelsing** [comment]
Has this been added yet?

**Comment by sandammeer** [comment]
Hey @SebastianThiebaud, @brunodelsing,

I will add this some time in october. If you need this feature faster you can always feel free to open a pull request :)

**Comment by sandammeer** [comment]
Hey @SebastianThiebaud, @brunodelsing,
I am currently working on the Cocoapods support, it will be available soon: #4

**Comment by sandammeer** [comment]
Cocoapods is now supported! 

Add this to your Podfile to install: 
`pod 'GoogleMapsTileOverlay', '~> 0.4.0'`
